version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: apollo-server-express
    versions:
    - 2.19.2
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.2
  - dependency-name: graphql-tools
    versions:
    - 7.0.2
    - 7.0.3
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: stylelint-config-standard
    versions:
    - 20.0.0
  - dependency-name: "@babel/plugin-syntax-jsx"
    versions:
    - 7.12.1
