type Mutation {
    addGenre(input: GenreInput!): Genre
    updateGenre(input: GenreInput!): Genre
    deleteGenre(name: String): Boolean

    addManga(input: MangaInput!): Manga
    updateManga(input: MangaInput!): Manga
    deleteManga(id: Int): Boolean
}

type Query {
    mangas: [Manga!]!
    manga(name: String): Manga

    genres: [Genre!]!
    genre(name: String): Genre

    # chapters: [Chapter!]!
}
