type Image {
    id: Int!
    name: String!
    url: String!
    chapter: Chapter!
    manga: Manga!
    # deletehash: String // Not public
}

input ImageInput {
    name: String!
    file: Upload!
    chapterId: String
}
