type Image {
    id: Int!
    name: String!
    url: String!
    # deletehash: String // Not public
    chapter: Chapter!
    manga: Manga!
}

input ImageInput {
    name: String!
    file: Upload!
    chapter: String
    Manga: String
}
