type Manga {
    id: Int!
    name: String!
    associatedNames: [String!]!
    type: MangaType!
    status: StatusType!
    publishedFrom: Date!
    publishedTo: Date!
    genres: [Genre!]!
    authors: String!
    description: String!
    chapters: [Chapter!]!

    image: Image
}

input MangaInput {
    id: Int!
    name: String!
    associatedNames: [String!]!
    type: MangaType!
    status: StatusType!
    publishedFrom: Date!
    publishedTo: Date!
    genres: [String!]!
    authors: String!
    description: String!
}
